[project]
name = "spin-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "componentize-py>=0.17.2",
    "spin-sdk>=3.3.1",
]
