spin_manifest_version = 2

[application]
name = "spin-py"
version = "0.1.0"
description = ""

[[trigger.http]]
route = "/..."
component = "hello-world"

[component.hello-world]
source = "main.wasm"

[component.hello-world.build]
command = "uv run --no-editable componentize-py -w spin-http componentize spin_py_demo -o main.wasm"
watch = ["src/**/*", "pyproject.toml"]
