spin_manifest_version = 2

[application]
name = "spin-py-demo"
version = "0.1.0"
description = "a demo of a spin wasm app made with uv and python"
authors = ["Дамјан Георгиевски <gdamjan@gmail.com>"]

[[trigger.http]]
route = "/..."
component = "main"

[component.main]
source = "main.wasm"

[component.main]
command = "uv run --no-editable componentize-py -w spin-http componentize spin_py_demo -o main.wasm"
watch = ["src/**/*", "pyproject.toml"]
